server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/extvaldb?useTimezone=true&serverTimezone=UTC
    username: dbserviceUser
    password: dbservicePassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
